name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Copy WAR file
        run: cp target/myweb-8.2.0.war myweb-8.2.0.war

      - name: Deploy to Tomcat
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "myweb-8.2.0.war"
          target: "/C/Program Files/Apache Software Foundation/Tomcat 9.0_Tomcat9cicd/webapps"
          port: 22
          timeout: 120s
          command_timeout: 10m

      - name: Restart Tomcat
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            net stop Tomcat9
            net start Tomcat9 
