name: Build, Dockerize, and Deploy to ECS

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build Maven Project and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-west-2  # Specify your AWS region here
          mask-password: true
          registry-type: private
          skip-logout: false
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64
          JAVA_HOME_11_X64: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/11.0.25-9/x64

      # Step 4: Build the Java application with Maven
      - name: Build Java Application
        run: mvn clean package -DskipTests

      # Step 5: Build and push Docker image to ECR
      - name: Build and Push Docker Image
        run: |
          REGION=us-west-2 # Update with your AWS region
          IMAGE_NAME=myweb
          REPO_URI=${{ secrets.ECR_REPO_URI }}

          # Build the Docker image
          docker build -t $IMAGE_NAME .

          # Tag the image
          docker tag $IMAGE_NAME:latest $REPO_URI:latest

          # Push the image to ECR
          docker push $REPO_URI:latest

  deploy:
    name: Deploy to ECS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      # Step 1: Update ECS Service
      - name: Update ECS Service
        run: |
          REGION=us-east-1 # Update with your AWS region
          CLUSTER_NAME=myweb-cluster
          SERVICE_NAME=tomcatservice
          REPO_URI=${{ secrets.ECR_REPO_URI }}

          aws ecs update-service \
            --cluster $CLUSTER_NAME \
            --service $SERVICE_NAME \
            --force-new-deployment \
            --region $REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
